# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions


name: Generate Cypress Report
on:
  push:
    branches:
      -'master'
      
jobs:
  cypress-test:
    name: Run on Chrome 83
    runs-on: ubuntu-latest
    container: cypress/browsers:node12.18.o-chrome83-ff77
    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Install cypress and verify
      run:
        npm ci
        $(npm bin) /cypress verify
    
    - name: Run Cypress tests
      run: npm run test:chrome
      continue-on-error: false
      
    - name: Copy test execution videos and screenshots shows
      run:
        mkdir public
        cp -r cypress/videos public/videos
        cp -r cypress/screenshots public/screenshots
        
    - name: Merge test reports
      run: npm run combine:report
      
    - name: Generate HTML report
      run: npm run generate:report
        
    - name: Deploy report page to GitHub Page
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
      
    
          
       
 
